<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_adicionar</name>
   <tag></tag>
   <elementGuidId>b17ebee3-7b3c-4282-91c4-f961322e22ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='formDetalleCartera:dataGridDatosBien:1:idBtnAdicionarDireccion']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'formDetalleCartera:dataGridDatosBien:1:idBtnAdicionarDireccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDetalleCartera:dataGridDatosBien:1:idBtnAdicionarDireccion</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='formDetalleCartera:dataGridDatosBien:1:idBtnAdicionarDireccion']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/span</value>
   </webElementXpaths>
</WebElementEntity>
