<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_departamentoJuzg</name>
   <tag></tag>
   <elementGuidId>a4ef044d-89e9-47ef-b3fd-ce8442c8906a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='formDireccionJuz:tablaSelectDep']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formDireccionJuz:tablaSelectDep&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDireccionJuz:tablaSelectDep</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formDireccionJuz:tablaSelectDep</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,p:&quot;formDireccionJuz:tablaSelectDep&quot;,u:&quot;formDireccionJuz:tablaSelectCiudad&quot;});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	
	Amazonas
	Antioquia
	Arauca
	Atlantico
	Bogota D.c.
	Bolivar
	Boyaca
	Caldas
	Caqueta
	Casanare
	Cauca
	Cesar
	Choco
	Cordoba
	Cundinamarca
	Desconocido
	Guainia
	Guaviare
	Huila
	La Guajira
	Magdalena
	Meta
	N. De Santander
	Nariño
	Polca
	Putumayo
	Quindio
	Risaralda
	S.andres Y Providencia
	Santander
	Sucre
	Tolima
	Valle Del Cauca
	Vaupes
	Vichada
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formDireccionJuz:tablaSelectDep&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='formDireccionJuz:tablaSelectDep']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='formDireccionJuz:panelFiltroJuzgado']/tbody/tr/td/table/tbody/tr[5]/td/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/form/fieldset/div/table/tbody/tr/td/table/tbody/tr[5]/td/select</value>
   </webElementXpaths>
</WebElementEntity>
