<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_adicionar</name>
   <tag></tag>
   <elementGuidId>0ada6d3a-6f4b-4f10-b806-45a1c748c0e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='formDetalleCartera:dataGridDatosBien:7:idBtnAdicionarDireccion']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formDetalleCartera:dataGridDatosBien:7:idBtnAdicionarDireccion&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDetalleCartera:dataGridDatosBien:7:idBtnAdicionarDireccion</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formDetalleCartera:dataGridDatosBien:7:idBtnAdicionarDireccion&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='formDetalleCartera:dataGridDatosBien:7:idBtnAdicionarDireccion']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/span</value>
   </webElementXpaths>
</WebElementEntity>
