<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldset_alertaAcumulacion</name>
   <tag></tag>
   <elementGuidId>b6c01fc0-7339-4b63-a69c-732065756af1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formInvestigacionControl:alertaNoRevision&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formInvestigacionControl:alertaNoRevision&quot;]</value>
   </webElementProperties>
</WebElementEntity>
