<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mensaje</name>
   <tag></tag>
   <elementGuidId>d2e97f33-17b6-4d5d-965a-97ff55b55b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formDetalleRevisionExpediente:growl_container&quot;]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formDetalleRevisionExpediente:growl_container&quot;]/div</value>
   </webElementProperties>
</WebElementEntity>
